import type { ProfileField } from "@/components/forms/auth-form.types";

const yesNoOptions = ["Yes", "No"];

export const roleProfileFields: Record<string, ProfileField[]> = {
  professor: [
    { name: "facultyId", label: "Faculty ID", placeholder: "FAC-1024", required: true },
    {
      name: "researchDomains",
      label: "Research Domains",
      placeholder: "AI, Robotics, Biotechnology",
      type: "tags",
      required: true,
    },
    { name: "publications", label: "Publications / Papers", type: "number", placeholder: "12", required: true },
    { name: "patents", label: "Patents", placeholder: "Granted or filed patent details" },
    { name: "universityName", label: "University Name", placeholder: "IIT Delhi", required: true },
    {
      name: "coursesTeaching",
      label: "Courses Teaching",
      placeholder: "Machine Learning, Control Systems",
      type: "tags",
      required: true,
    },
    {
      name: "availableForMentorship",
      label: "Available for Mentorship",
      type: "select",
      options: yesNoOptions,
      required: true,
    },
    { name: "fundedProjects", label: "Funded Projects", placeholder: "DST project on..." },
    { name: "portfolioWebsite", label: "Portfolio Website", type: "url", placeholder: "https://..." },
    { name: "orcidId", label: "ORCID ID", placeholder: "0000-0000-0000-0000" },
    { name: "researchGate", label: "ResearchGate", type: "url", placeholder: "https://..." },
    { name: "googleScholar", label: "Google Scholar", type: "url", placeholder: "https://..." },
  ],
  researcher: [
    { name: "researchArea", label: "Research Area", placeholder: "Human-computer interaction", required: true },
    { name: "publishedPaperCount", label: "Published Paper Count", type: "number", placeholder: "4", required: true },
    { name: "currentResearchTopic", label: "Current Research Topic", placeholder: "Explainable AI", required: true },
    {
      name: "openToCollaboration",
      label: "Open to Collaboration",
      type: "select",
      options: yesNoOptions,
      required: true,
    },
    { name: "domains", label: "Domains", placeholder: "AI, Healthcare, Education", type: "tags", required: true },
    { name: "labOrCenter", label: "Lab / Center", placeholder: "Cognitive Systems Lab", required: true },
    { name: "universityName", label: "University Name", placeholder: "IISc Bengaluru", required: true },
  ],
  industry: [
    { name: "companyName", label: "Company Name", placeholder: "Tata Elxsi", required: true },
    { name: "industrySector", label: "Industry Sector", placeholder: "Automotive", required: true },
    { name: "domains", label: "Domains", placeholder: "IoT, Edge AI", type: "tags", required: true },
    { name: "jobRole", label: "Job Role", placeholder: "Innovation Lead", required: true },
    {
      name: "problemsInterestedIn",
      label: "Problems Interested In",
      placeholder: "Predictive maintenance, automation",
      type: "tags",
      required: true,
    },
    { name: "hiringInterns", label: "Hiring Interns", type: "select", options: yesNoOptions, required: true },
    { name: "companyWebsite", label: "Company Website", type: "url", placeholder: "https://..." },
    { name: "idCardProof", label: "ID Card Proof", placeholder: "Employee ID or proof link" },
  ],
  founder: [
    { name: "startupName", label: "Startup Name", placeholder: "NeuroGrid Labs", required: true },
    { name: "startupDomain", label: "Startup Domain", placeholder: "Deep tech", required: true },
    { name: "stage", label: "Stage", placeholder: "Prototype / MVP / Revenue", required: true },
    { name: "teamSize", label: "Team Size", type: "number", placeholder: "5", required: true },
    { name: "fundingStatus", label: "Funding Status", placeholder: "Bootstrapped", required: true },
    {
      name: "startupDescription",
      label: "Startup Details",
      placeholder: "What the startup builds and who it serves",
      type: "textarea",
      required: true,
    },
    { name: "startupWebsite", label: "Startup Website", type: "url", placeholder: "https://..." },
    { name: "incubationStatus", label: "Incubation Status", placeholder: "Incubated / Applying / Not yet" },
    { name: "url", label: "Deck / Product URL", type: "url", placeholder: "https://..." },
  ],
  incubator: [
    { name: "incubationName", label: "Incubation Name", placeholder: "CISER Incubation Cell", required: true },
    {
      name: "supportedDomains",
      label: "Supported Domains",
      placeholder: "AI, Climate, Hardware",
      type: "tags",
      required: true,
    },
    { name: "startupsSupportedCount", label: "Startups Supported", type: "number", placeholder: "25", required: true },
    { name: "fundingAvailable", label: "Funding Available", type: "select", options: yesNoOptions, required: true },
    { name: "website", label: "Website", type: "url", placeholder: "https://..." },
    { name: "applicationLink", label: "Application Link", type: "url", placeholder: "https://..." },
    { name: "acceptanceCriteria", label: "Acceptance Criteria", placeholder: "Eligibility or selection notes" },
    { name: "preferencePlans", label: "Preference Plans", placeholder: "Preferred sectors, cohorts, or support model" },
  ],
  investor: [
    { name: "investmentFirmName", label: "Investment Firm", placeholder: "Catalyst Ventures", required: true },
    {
      name: "investmentDomains",
      label: "Investment Domains",
      placeholder: "SaaS, MedTech, Climate",
      type: "tags",
      required: true,
    },
    { name: "investmentRange", label: "Investment Range", placeholder: "10L - 1Cr", required: true },
    { name: "portfolioCompaniesCount", label: "Portfolio Companies", type: "number", placeholder: "18", required: true },
    { name: "openToMentor", label: "Open to Mentor", type: "select", options: yesNoOptions, required: true },
    { name: "funding", label: "Funding", placeholder: "Seed / angel / grant support" },
    {
      name: "interestedStartupStages",
      label: "Interested Startup Stages",
      placeholder: "Idea, MVP, Revenue",
      type: "tags",
    },
  ],
  student: [
    { name: "collegeName", label: "College Name", placeholder: "NIT Trichy", required: true },
    { name: "degree", label: "Degree", placeholder: "B.Tech", required: true },
    { name: "branch", label: "Branch", placeholder: "Computer Science", required: true },
    { name: "yearOfStudy", label: "Year of Study", placeholder: "3rd year", required: true },
    {
      name: "areasOfInterest",
      label: "Areas of Interest",
      placeholder: "AI, Web, Electronics",
      type: "tags",
      required: true,
    },
    { name: "interestedInInternship", label: "Interested in Internship", type: "select", options: yesNoOptions, required: true },
    { name: "hackathons", label: "Hackathons", placeholder: "Smart India Hackathon finalist" },
    { name: "industryExperience", label: "Industry Experience", placeholder: "Internship or project experience" },
  ],
};
